# Generated by Django 4.2.3 on 2023-07-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('PhoneNumber', models.CharField(max_length=13)),
                ('message', models.CharField(max_length=30)),
            ],
        ),
    ]
